# Configuration file for edge index generation

# ---------------------------------
h5_data_file: "/home/amaterasu/work/mini-Caverns/h5_data/hierarchical_e-_50-1500MeV_folder3_a5.h5"  
output_file: "/home/amaterasu/work/mini-Caverns/h5_edges/knn5_st_e-_50-1500MeV_folder3_a5.h5"

# File handling approach
combine_files: false  # true: add edges to data file, false: create separate edge file

pos_features: ["hitx", "hity", "hitz", "pmt_time"]  # Features from HDF5 to use for edge construction

metric: "spacetime"          # Options: spacetime, euclidean_3d, weighted_euclidean, or null for no transformation
# Metric parameters (optional)
# metric_params: null

algorithm: "knn_pyg"  # Options: knn_pyg, knn_scipy, delaunay, radius
algorithm_params:
  k: 5  


# HDF5 settings
compression: "gzip"  # Options: "gzip", "lzf", "none"
overwrite: false  # Whether to overwrite existing edge datasets

# Monitoring settings
use_timeit: true  # Measure computation time 
monitor_ram: true
monitor_interval: 500  # Check RAM every N events