


h5_data_file: "/home/amaterasu/work/mini-Caverns/h5_data/hierarchical_e-_50-1500MeV_folder3_a5.h5"
output_file: "/home/amaterasu/work/mini-Caverns/h5_edges/e-_50-1500MeV_folder3_a5_spatial_cut_Lt_knn5.h5"

# File handling approach
combine_files: false  # true: add edges to data file, false: create separate edge file

# Single selection
node_selection:
  type: percentile
  lower_percentile: 5.0
  upper_percentile: 90.0
  use_landau_fit: true

# -- Define the metric space ---
pos_features: ["hitx", "hity", "hitz"]  # Features from HDF5 to use for edge construction
metric: null          # Options: spacetime, weighted_euclidean, or null for no transformation (= raw knn)
# metric_params: null # (optional)

# Define the algorithm
algorithm: "knn_pyg"  # Options: knn_pyg, knn_scipy, delaunay, radius
algorithm_params:
  k: 5  


# HDF5 settings
compression: "gzip"  # Options: "gzip", "lzf", "none"
overwrite: true  # Whether to overwrite existing edge datasets

# Monitoring settings
use_timeit: true  # Measure computation time 
monitor_ram: false
monitor_interval: 500  # Check RAM every N events